TILE_SIZE = 24
OFFSET_COLS = 0
OFFSET_ROWS = 2
VIEWPORT_ROWS = 16
VIEWPORT_COLS = 16
VIEWPORT = dict(x1=OFFSET_COLS, x2=OFFSET_COLS + VIEWPORT_COLS,
                y1=OFFSET_ROWS, y2=OFFSET_ROWS + VIEWPORT_ROWS)
